version: 2.1

orbs:
  maven: circleci/maven@1.0.0

executors:
  jdk11:
    docker:
    - image: cimg/openjdk:11.0

workflows:
  maven_test:
    jobs:
      - maven/test:
          command: 'test'
          executor: jdk11
