version: 2.1

executors:
  jdk11:
    docker:


jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
      - run:
          name: Cache m2 artifacts
          command: mvn dependency:go-offline
      - save_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
          paths: [ "~/.m2" ]
  test:
    docker:
      - image: cimg/openjdk:11.0
    parameters:
      mysql:
        type: string
    environment:
      MYSQL_VERSION: "<< parameters.mysql >>"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
      - run:
          name: testit
          command: mvn test
      - store_artifacts:
          path: test.log

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          mysql: "5.5"
          requires: [ "build" ]
      - test:
          mysql: "5.7"
          requires: [ "build" ]
      - test:
          mysql: "8.0"
          requires: [ "build" ]

