version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
      - run:
          name: Cache m2 artifacts
          command: mvn dependency:go-offline
      - save_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
          paths: [ "~/.m2" ]
      - run:
          name: testit
          command: mvn test
      - store_artifacts:
          path: test.log

workflows:
  version: 2
  build_and_test:
    jobs:
      - test

